python train.py \
  --data-root data/demo_data/insertion_usb \
  --task insertion_usb \
  --vision-key front \
  --vision-type image \
  --image-size 224 \
  --use-tactile \
  --tactile-key tactile_force_field_right \
  --tactile-in-channels 3 \
  --tactile-height 10 \
  --tactile-width 14 \
  --tactile-dim 64 \
  --fusion-type concat \
  --reg-loss-type vc \
  --reg-on-vision-only \
  --batch-size 64 \
  --epochs 560