python eval_planner.py \
  --data-root data/demo_data/exploration_search \
  --ckpt-path logs/ckpts/exploration_search/pointcloud/vc/tactile_rgb_right/concat/100000.ckpt \
  --isaacgym-cfg-name isaacgym_config_search \
  --output-dir logs/planning/exploration_search/100000/step_36/pc_rgb \
  --vision-key pointcloud \
  --vision-type pc \
  --pc-in-channels 6 \
  --use-tactile \
  --tactile-key tactile_rgb_right \
  --tactile-in-channels 3 \
  --tactile-height 80 \
  --tactile-width 60 \
  --fusion-type concat \
  --reg-loss-type vc \
  --reg-on-vision-only \
  --history-size 1 \
  --horizon 6 \
  --candidates 100 \
  --topk 8 \
  --iterations 4 \
  --num-envs 100 \
  --num-record 6 \
  --goal-offset-steps 36 \
  --max-steps 45 \
  --stop-on-success