  python train.py \
    --data-root data/demo_data/insertion_peg \
    --task insertion_peg \
    --vision-key pointcloud \
    --vision-type pc \
    --pc-in-channels 6 \
    --use-tactile \
    --tactile-key tactile_depth_right \
    --tactile-in-channels 1 \
    --tactile-height 80 \
    --tactile-width 60 \
    --fusion-type concat \
    --reg-loss-type vc \
    --reg-on-vision-only \
    --batch-size 64 \
    --epochs 560