python eval_rollout.py \
  --ckpt-path logs/ckpts/screwing_bulb/pointcloud/vc/only/100000.ckpt \
  --data-root /home/zhiyuan/Project/TVB/data/screwing_bulb \
  --vision-key pointcloud \
  --vision-type pc \
  --pc-in-channels 6 \
  --reg-loss-type vc \
  --history-size 1 \
  --max-rollout 6 \
  --action-mode all \
  --output-dir logs/rollout/screwing_bulb/pc