python eval_planner.py \
  --data-root data/demo_data/screwing_bulb \
  --ckpt-path logs/ckpts/screwing_bulb/front/vc/tactile_rgb_right/concat/100000.ckpt \
  --isaacgym-cfg-name isaacgym_config_bulb \
  --output-dir logs/planning/screwing_bulb/100000/step_36/front_rgb \
  --vision-key front \
  --vision-type image \
  --image-size 224 \
  --use-tactile \
  --tactile-key tactile_rgb_right \
  --tactile-in-channels 3 \
  --tactile-height 80 \
  --tactile-width 60 \
  --fusion-type concat \
  --reg-loss-type vc \
  --reg-on-vision-only \
  --history-size 1 \
  --horizon 6 \
  --candidates 100 \
  --topk 8 \
  --iterations 4 \
  --num-envs 100 \
  --num-record 6 \
  --goal-offset-steps 36 \
  --max-steps 45 \
  --quat-thresh-deg 5 \
  --stop-on-success