python train.py \
  --task screwing_nut \
  --data-root /home/zhiyuan/Project/TVB/data/screwing_nut \
  --vision-key pointcloud \
  --vision-type pc \
  --pc-in-channels 6 \
  --use-tactile \
  --tactile-key tactile_depth_right \
  --tactile-in-channels 1 \
  --tactile-height 80 \
  --tactile-width 60 \
  --reg-loss-type vc \
  --fusion-type attn \
  --batch-size 64 \
  --epochs 160
