python train.py \
  --data-root /home/zhiyuan/Project/TVB/data/screwing_nut \
  --vision-key pointcloud \
  --vision-type pc \
  --pc-in-channels 6 \
  --use-tactile \
  --tactile-key tactile_force_field_right \
  --tactile-in-channels 3 \
  --tactile-height 10 \
  --tactile-width 14 \
  --fusion-type film \
  --reg-loss-type vc \
  --batch-size 64 \
  --epochs 160
