data_root: /scratch/gilbreth/zhou1458/manifeel_isaacgym/manifeel/data/insertion_usb_zhiyuan
task: usb

encoder: dino
vision_key: pointcloud
vision_type: pc
pc_in_channels: 6
pointcloud_scale: 0.4
pc_tokenizer: voxel
pc_num_points: 256
pc_order_mode: none
pc_voxel_grid: [16, 16, 1]
pc_bounds: [-0.4, 0.8, -0.6, 0.6, -0.2, 0.8]
image_size: 224
frameskip: 1
num_steps: 6

dino_name: dinov3_vitb16
dino_checkpoint: /scratch/gilbreth/zhou1458/manifeel_isaacgym/manifeel/manifeel/world_model_tf/wm_tf_data/pretrianed_model/dino3/dinov3_vitb16_pretrain_lvd1689m-73cec8be.pth
dino_token_mode: patch
dino_token_strategy: patch_only
dino_last_layers: 4

use_tactile: true
tactile_key: tactile_force_field_right
tactile_height: 10
tactile_width: 14
tactile_pool_mode: attention

lowdim_keys: ee_pos,ee_quat,plug_pos,plug_quat,socket_pos_gt

exp_name: usb/pc_pointcloud_ff_voxel256_vc
batch_size: 96
num_workers: 8
train_num_workers: 8
val_num_workers: 4
pin_memory: true
persistent_workers: true
prefetch_factor: 3
epochs: 500
train_ratio: 0.9
split_seed: 3072
lr: 0.0001
weight_decay: 0.0001
save_dir: outputs/world_model_tf/usb/pointcloud_ff_voxel256
save_every_n_epochs: 30
resume_from:
early_stop_patience: 20
early_stop_monitor: val/rollout_visual_l2
early_stop_mode: min

predictor_embed_dim: 384
predictor_depth: 6
predictor_heads:
predictor_mlp_ratio: 4.0
drop_rate: 0.0
attn_drop_rate: 0.0
drop_path_rate: 0.0

visual_l2_weight: 1.0
visual_cos_weight: 0.0
lowdim_l2_weight: 1.0
lowdim_cos_weight: 0.0
tactile_l2_weight: 1.0
tactile_cos_weight: 0.0

reg_loss_type: vc
reg_weight: 1.0
cov_coeff: 1.0
std_coeff: 1.0
sigreg_coeff: 0.1
sigreg_knots: 17
sigreg_num_proj: 1024
sim_coeff_t: 0.1
idm_coeff: 0.1

rollout_ctxt_window: 4
rollout_steps: 2
val_proprio_rollout_mode: predict_proprio
precision: bf16-mixed

wandb: true
wandb_project: manifeel_wm_tf_usb
wandb_entity:
wandb_name:
wandb_save_dir: outputs/wandb
wandb_log_model: false
