python eval_rollout.py \
  --ckpt-path ckpts/wrist_tacdepth/100000.ckpt \
  --data-root /home/zhiyuan/Project/TVB/data/insertion_usb \
  --vision-key wrist \
  --vision-type image \
  --image-size 224 \
  --use-tactile \
  --tactile-key tactile_depth_right \
  --tactile-in-channels 1 \
  --tactile-height 80 \
  --tactile-width 60 \
  --fusion-type concat \
  --reg-loss-type vc \
  --reg-on-vision-only-for-concat \
  --history-size 1 \
  --max-rollout 6 \
  --action-mode all \
  --output-dir rollout/wrist_tacdepth