python eval_rollout.py \
  --ckpt-path logs/ckpts/insertion_usb/front/vc/tactile_depth_right/concat/100000.ckpt \
  --data-root data/demo_data/insertion_usb \
  --vision-key front \
  --vision-type image \
  --image-size 224 \
  --use-tactile \
  --tactile-key tactile_depth_right \
  --tactile-in-channels 1 \
  --tactile-height 80 \
  --tactile-width 60 \
  --fusion-type concat \
  --reg-loss-type vc \
  --reg-on-vision-only \
  --history-size 1 \
  --max-rollout 6 \
  --action-mode all \
  --output-dir logs/rollout/front_tacdepth