  python train.py \
    --data-root data/demo_data/exploration_sorting_normal \
    --task exploration_sorting_normal \
    --vision-key front \
    --vision-type image \
    --image-size 224 \
    --use-tactile \
    --tactile-key tactile_rgb_right \
    --tactile-in-channels 3 \
    --tactile-height 80 \
    --tactile-width 60 \
    --fusion-type concat \
    --reg-loss-type vc \
    --reg-on-vision-only \
    --batch-size 64 \
    --epochs 642