python train.py \
  --data-root data/demo_data/screwing_nut \
  --task screwing_nut \
  --vision-key pointcloud \
  --vision-type pc \
  --pc-in-channels 6 \
  --use-tactile \
  --tactile-key tactile_force_field_right \
  --tactile-in-channels 3 \
  --tactile-height 10 \
  --tactile-width 14 \
  --tactile-dim 128 \
  --fusion-type concat \
  --reg-loss-type vc \
  --reg-on-vision-only \
  --batch-size 64 \
  --epochs 160