python eval_planner.py \
  --data-root data/screwing_bulb \
  --ckpt-path logs/ckpts/screwing_bulb_rgb/pc/100000.ckpt \
  --isaacgym-cfg-name isaacgym_config_bulb \
  --output-dir logs/planning/screwing_bulb/100000/step_12/pc_tacrgb \
  --vision-key pointcloud \
  --vision-type pc \
  --pc-in-channels 6 \
  --use-tactile \
  --tactile-key tactile_rgb_right \
  --tactile-in-channels 3 \
  --tactile-height 80 \
  --tactile-width 60 \
  --fusion-type concat \
  --reg-loss-type vc \
  --reg-on-vision-only \
  --history-size 1 \
  --horizon 6 \
  --candidates 100 \
  --topk 8 \
  --iterations 4 \
  --num-envs 100 \
  --num-record 6 \
  --goal-offset-steps 12 \
  --max-steps 15 \
  --stop-on-success